/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AffiliateDisclosureRouteImport } from './routes/affiliate-disclosure'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminGuidesRouteImport } from './routes/admin/guides'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as GuidesSlugRouteImport } from './routes/guides.$slug'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as AdminIntelligenceDealsRouteImport } from './routes/admin/intelligence/deals'
import { Route as AdminIntelligenceSearchDemandRouteImport } from './routes/admin/intelligence/search-demand'
import { Route as AdminIntelligenceTrendingRouteImport } from './routes/admin/intelligence/trending'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminResearchIndexRouteImport } from './routes/admin/research/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateDisclosureRoute = AffiliateDisclosureRouteImport.update({
  id: '/affiliate-disclosure',
  path: '/affiliate-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGuidesRoute = AdminGuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntelligenceDealsRoute = AdminIntelligenceDealsRouteImport.update({
  id: '/intelligence/deals',
  path: '/intelligence/deals',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminIntelligenceSearchDemandRoute =
  AdminIntelligenceSearchDemandRouteImport.update({
    id: '/intelligence/search-demand',
    path: '/intelligence/search-demand',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminIntelligenceTrendingRoute =
  AdminIntelligenceTrendingRouteImport.update({
    id: '/intelligence/trending',
    path: '/intelligence/trending',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminResearchIndexRoute = AdminResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => AdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/deals': typeof DealsRoute
  '/guides': typeof GuidesRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/intelligence/deals': typeof AdminIntelligenceDealsRoute
  '/admin/intelligence/search-demand': typeof AdminIntelligenceSearchDemandRoute
  '/admin/intelligence/trending': typeof AdminIntelligenceTrendingRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/research/': typeof AdminResearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/deals': typeof DealsRoute
  '/guides': typeof GuidesRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/intelligence/deals': typeof AdminIntelligenceDealsRoute
  '/admin/intelligence/search-demand': typeof AdminIntelligenceSearchDemandRoute
  '/admin/intelligence/trending': typeof AdminIntelligenceTrendingRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/research': typeof AdminResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/affiliate-disclosure': typeof AffiliateDisclosureRoute
  '/deals': typeof DealsRoute
  '/guides': typeof GuidesRouteWithChildren
  '/search': typeof SearchRoute
  '/admin/guides': typeof AdminGuidesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/product/$slug': typeof ProductSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/intelligence/deals': typeof AdminIntelligenceDealsRoute
  '/admin/intelligence/search-demand': typeof AdminIntelligenceSearchDemandRoute
  '/admin/intelligence/trending': typeof AdminIntelligenceTrendingRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/research/': typeof AdminResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/affiliate-disclosure'
    | '/deals'
    | '/guides'
    | '/search'
    | '/admin/guides'
    | '/admin/login'
    | '/admin/settings'
    | '/guides/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/admin/intelligence/deals'
    | '/admin/intelligence/search-demand'
    | '/admin/intelligence/trending'
    | '/admin/products/'
    | '/admin/research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliate-disclosure'
    | '/deals'
    | '/guides'
    | '/search'
    | '/admin/guides'
    | '/admin/login'
    | '/admin/settings'
    | '/guides/$slug'
    | '/product/$slug'
    | '/admin'
    | '/admin/intelligence/deals'
    | '/admin/intelligence/search-demand'
    | '/admin/intelligence/trending'
    | '/admin/products'
    | '/admin/research'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/affiliate-disclosure'
    | '/deals'
    | '/guides'
    | '/search'
    | '/admin/guides'
    | '/admin/login'
    | '/admin/settings'
    | '/guides/$slug'
    | '/product/$slug'
    | '/admin/'
    | '/admin/intelligence/deals'
    | '/admin/intelligence/search-demand'
    | '/admin/intelligence/trending'
    | '/admin/products/'
    | '/admin/research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AffiliateDisclosureRoute: typeof AffiliateDisclosureRoute
  DealsRoute: typeof DealsRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  SearchRoute: typeof SearchRoute
  ProductSlugRoute: typeof ProductSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-disclosure': {
      id: '/affiliate-disclosure'
      path: '/affiliate-disclosure'
      fullPath: '/affiliate-disclosure'
      preLoaderRoute: typeof AffiliateDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/guides': {
      id: '/admin/guides'
      path: '/guides'
      fullPath: '/admin/guides'
      preLoaderRoute: typeof AdminGuidesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/intelligence/deals': {
      id: '/admin/intelligence/deals'
      path: '/intelligence/deals'
      fullPath: '/admin/intelligence/deals'
      preLoaderRoute: typeof AdminIntelligenceDealsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/intelligence/search-demand': {
      id: '/admin/intelligence/search-demand'
      path: '/intelligence/search-demand'
      fullPath: '/admin/intelligence/search-demand'
      preLoaderRoute: typeof AdminIntelligenceSearchDemandRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/intelligence/trending': {
      id: '/admin/intelligence/trending'
      path: '/intelligence/trending'
      fullPath: '/admin/intelligence/trending'
      preLoaderRoute: typeof AdminIntelligenceTrendingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/research/': {
      id: '/admin/research/'
      path: '/research'
      fullPath: '/admin/research/'
      preLoaderRoute: typeof AdminResearchIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminGuidesRoute: typeof AdminGuidesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminIntelligenceDealsRoute: typeof AdminIntelligenceDealsRoute
  AdminIntelligenceSearchDemandRoute: typeof AdminIntelligenceSearchDemandRoute
  AdminIntelligenceTrendingRoute: typeof AdminIntelligenceTrendingRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminResearchIndexRoute: typeof AdminResearchIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminGuidesRoute: AdminGuidesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminIntelligenceDealsRoute: AdminIntelligenceDealsRoute,
  AdminIntelligenceSearchDemandRoute: AdminIntelligenceSearchDemandRoute,
  AdminIntelligenceTrendingRoute: AdminIntelligenceTrendingRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminResearchIndexRoute: AdminResearchIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AffiliateDisclosureRoute: AffiliateDisclosureRoute,
  DealsRoute: DealsRoute,
  GuidesRoute: GuidesRouteWithChildren,
  SearchRoute: SearchRoute,
  ProductSlugRoute: ProductSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
